### ISSUE TITLE
Can't reproduce results even set all random seeds 

### ISSUE THREAD

**Issue by starry-y** [xufangzhi/Logiformer#3]
Hello, I run the code without any changing.

In this condition, I run the code twice but can't reproduce the results.

Do you have the same situation and how you solve this problem? 

Thanks a lot!

**Comment by xufangzhi** [comment]
Thanks for your attention to our work. But we do not have the same situation during the experiments. Since you run the code without any changes, I think it is necessary to check the version of some required packages (e.g., numpy).
